### ISSUE TITLE
`Timeline Delegate` - didStop not being called.

### ISSUE THREAD

**Issue by andreymitkoch** [createwithflow/FlowCommoniOS#26]
Animation seems to work correctly, however `didStop` function does not seem to be called. Moreover, variable `Timeline().playing` never changes from `true` to `false`. 

```swift
extension SomeViewController: TimelineDelegate {
    
    func didReset(timeline: Timeline) {
        
    }
    
    func didPlay(timeline: Timeline) {
         //This function is working well
    }
    
    func didPause(timeline: Timeline) {
        
    }
    
    func didOffset(timeline: Timeline, to time: TimeInterval) {
        
    }
    
    func didStop(timeline: Timeline) {
        //This function is never called
    }

}
```

**Comment by andreymitkoch** [comment]
@jbeenie @ismailgulek @Owen-Delisle @C4Framework

**Comment by C4Framework** [comment]
Hey Andrey,

I just tested and the delegate method `didStop` does get called for me.
If you have a sample project where it's not working, could you please provide a link so I can test.

Also, `Timeline().playing` won't work because `Timeline()` is constructing a new timeline when being called.
You will need to check `timeline.playing()` which should work as it is pointing to a previously constructed variable. 

Here's a sample project showing everything working:

https://www.dropbox.com/s/tokbcbvjl405jzb/Timeline.zip?dl=0

p.s. In investigating this ticket, I did find a small bug to fix which will come out in our next release.

Cheers,
Travis

**Comment by andreymitkoch** [comment]
Hey Travis,

Thank you for your prompt response.

Everything seems to work well on the file you shared with me. However, when
I try to set a similar delegate with my animation it seems to be called
multiple times (I speculate it calls didStop on every sub animation didStop
inside  main animation).

I attach some screenshots showing debugger output when I simply run my
animation. I am also attaching slightly adjusted (to include delegate)
auto-generated code I was using.

Kind regards,
Andrey
